#!/bin/bash
Senha=`zenity --password`
(
echo "10" ; sleep 0.1
echo "Updating sistem" ; echo $Senha | sudo -S  apt-get update
echo "20" ; sleep 0.1
echo "upgrading sistem" ; sudo apt-get upgrade
echo "50" ; sleep 0.1
echo "Instaling memteste" ; sudo apt install memtester
echo "100" ; sleep 0.1
)| zenity --progress\
	      --title="RODANDO"\
		  --text="Atualizando e instalando programas"\
		  --percentage=0\
		  --auto-close;  
		  
zenity --info --title="Shrek Update" --text="Sistema Atualizado com sucesso"




#sudo echo
 |
#zenity --progress \
#  --title="Update System Logs" \
#  --text="Scanning mail logs..." \
#  --percentage=0
#
#if [ "$?" = -1 ] ; then
#        zenity --error \
#          --text="Update canceled."
#fi
#
#zenity --info --title="Shrek Update" --text="
#|==========================|
#|       Sistema atualizado       |
#|==========================|
#"
#
#nome=$(zenity --title="Nome?" --text "Qual é o seu nome?" --entry)
#zenity --info --title="Boas-vindas" --text=" $nome" --width="100" height="50"
#sobrenome=$(zenity --title="Sobrenome" --text "$primeiro Qual é o seu sobrenome?" --entry)
#zenity --info --title="Bóson Treinamentos" --text="Bons estudos, $nome $sobrenome"
#
#
#echo "Entre com a senha: " 
#zenity --progress; sudo apt-get update 
#
#echo " 
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
# ⣿⠟⠫⢻⣿⣿⣿⣿⢟⣩⡍⣙⠛⢛⣿⣿⣿⠛⠛⠛⠛⠻⣿⣿⣿⣿⣿⡿⢿⣿
# ⣿⠤⠄⠄⠙⢿⣿⣿⣿⡿⠿⠛⠛⢛⣧⣿⠇⠄⠂⠄⠄⠄⠘⣿⣿⣿⣿⠁⠄⢻
# ⣿⣿⣿⣿⣶⣄⣾⣿⢟⣼⠒⢲⡔⣺⣿⣧⠄⠄⣠⠤⢤⡀⠄⠟⠉⣠⣤⣤⣤⣾
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣀⣬⣵⣿⣿⣿⣶⡤⠙⠄⠘⠃⠄⣴⣾⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢻⠿⢿⣿⣿⠿⠋⠁⠄⠂⠉⠒⢘⣿⣿⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⣿⡿⣡⣷⣶⣤⣤⣀⡀⠄⠄⠄⠄⠄⠄⠄⣾⣿⣿⣿⣿⣿⣿
# ⣿⣿⣿⣿⣿⣿⣿⡿⣸⣿⣿⣿⣿⣿⣿⣿⣷⣦⣰⠄⠄⠄⠄⢾⠿⢿⣿⣿⣿⣿
# ⣿⡿⠋⣡⣾⣿⣿⣿⡟⠉⠉⠈⠉⠉⠉⠉⠉⠄⠄⠄⠑⠄⠄⠐⡇⠄⠈⠙⠛⠋
# ⠋⠄⣾⣿⣿⣿⣿⡿⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢠⡇⠄⠄⠄⠄⠄
# ⠄⢸⣿⣿⣿⣿⣿⣯⠄⢠⡀⠄⠄⠄⠄⠄⠄⠄⠄⣀⠄⠄⠄⠄⠁⠄⠄⠄⠄⠄
# ⠁⢸⣿⣿⣿⣿⣿⣯⣧⣬⣿⣤⣐⣂⣄⣀⣠⡴⠖⠈⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
# ⠈⠈⣿⣟⣿⣿⣿⣿⣿⣿⣿⣿⣽⣉⡉⠉⠈⠁⠄⠁⠄⠄⠄⠄⡂⠄⠄⠄⠄⠄
# ⠄⠄⠙⣿⣿⠿⣿⣿⣿⣿⣷⡤⠈⠉⠉⠁⠄⠄⠄⠄⠄⠄⠄⠠⠔⠄⠄⠄⠄⠄
# ⠄⠄⠄⡈⢿⣷⣿⣿⢿⣿⣿⣷⡦⢤⡀⠄⠄⠄⠄⠄⠄⢐⣠⡿⠁⠄⠄⠄⠄⠄
#">> /home/testes/appzoom/Logs/interface_log.txt
#read 
#
#zenity --info --title="Shrek Test" --text="
#|==========================|
#|Arquivos Movidos com sucesso|
#|==========================|
#"
#