#!/bin/bash
echo ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
echo ⣿⠟⠫⢻⣿⣿⣿⣿⢟⣩⡍⣙⠛⢛⣿⣿⣿⠛⠛⠛⠛⠻⣿⣿⣿⣿⣿⡿⢿⣿
echo ⣿⠤⠄⠄⠙⢿⣿⣿⣿⡿⠿⠛⠛⢛⣧⣿⠇⠄⠂⠄⠄⠄⠘⣿⣿⣿⣿⠁⠄⢻
echo ⣿⣿⣿⣿⣶⣄⣾⣿⢟⣼⠒⢲⡔⣺⣿⣧⠄⠄⣠⠤⢤⡀⠄⠟⠉⣠⣤⣤⣤⣾
echo ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣀⣬⣵⣿⣿⣿⣶⡤⠙⠄⠘⠃⠄⣴⣾⣿⣿⣿⣿⣿
echo ⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢻⠿⢿⣿⣿⠿⠋⠁⠄⠂⠉⠒⢘⣿⣿⣿⣿⣿⣿⣿
echo ⣿⣿⣿⣿⣿⣿⣿⣿⡿⣡⣷⣶⣤⣤⣀⡀⠄⠄⠄⠄⠄⠄⠄⣾⣿⣿⣿⣿⣿⣿
echo ⣿⣿⣿⣿⣿⣿⣿⡿⣸⣿⣿⣿⣿⣿⣿⣿⣷⣦⣰⠄⠄⠄⠄⢾⠿⢿⣿⣿⣿⣿
echo ⣿⡿⠋⣡⣾⣿⣿⣿⡟⠉⠉⠈⠉⠉⠉⠉⠉⠄⠄⠄⠑⠄⠄⠐⡇⠄⠈⠙⠛⠋
echo ⠋⠄⣾⣿⣿⣿⣿⡿⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢠⡇⠄⠄⠄⠄⠄
echo ⠄⢸⣿⣿⣿⣿⣿⣯⠄⢠⡀⠄⠄⠄⠄⠄⠄⠄⠄⣀⠄⠄⠄⠄⠁⠄⠄⠄⠄⠄
echo ⠁⢸⣿⣿⣿⣿⣿⣯⣧⣬⣿⣤⣐⣂⣄⣀⣠⡴⠖⠈⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
echo ⠈⠈⣿⣟⣿⣿⣿⣿⣿⣿⣿⣿⣽⣉⡉⠉⠈⠁⠄⠁⠄⠄⠄⠄⡂⠄⠄⠄⠄⠄
echo ⠄⠄⠙⣿⣿⠿⣿⣿⣿⣿⣷⡤⠈⠉⠉⠁⠄⠄⠄⠄⠄⠄⠄⠠⠔⠄⠄⠄⠄⠄
echo ⠄⠄⠄⡈⢿⣷⣿⣿⢿⣿⣿⣷⡦⢤⡀⠄⠄⠄⠄⠄⠄⢐⣠⡿⠁⠄⠄⠄⠄⠄


sleep 0,2 
clear

echo "
§===========§
 FULL UPDATE
§===========§
"
sudo apt update && sudo apt full-upgrade
clear

echo "
§=======§
 UPDATED
§=======§
"
sleep 1
clear

#			================
#			INSTALANDO CUBIC
#			================	 
#sudo apt-add-repository ppa:cubic-wizard/release
# 
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6494C6D6997C215E
#
#sudo apt update && sudo apt install cubic
#
#			===============
#			CUBIC INSTALADO
#			===============
#clear	

echo "
§====================§
 INSTALANDO MEMTESTER
§====================§
"			
sudo apt-get install memtester
clear

echo "
§===================§
 MEMTESTER INSTALADO
§===================§	
"

sleep 1
clear

echo "
§=====================§
 INTALANDO STRESS TEST
§=====================§
"
sudo apt-get install stress
clear

echo "
§=====================§
 STRESS TEST INSTALADO
§=====================§
"
sleep 1
clear

echo "
§====================§
 INTALANDO LM-SENSORS
§====================§
"			
sudo apt install lm-sensors
clear

echo "
§====================§
 LM-SENSORS INSTALADO
§====================§
"

sleep 
clear

echo "
§===============================================§
 APPS INTALADOS E SISTEMA ATUALIZADO COM SUCESSO
§===============================================§
"
echo "PRECIONE QUALQUER TECLA PARA CONTINUAR"
read
clear