#!/bin/bash
echo "
§===========§
    UPDATE
§===========§
"

Senha=$(zenity --password)
echo "($Senha)" | sudo su

(
    echo "10"
        sleep 0.1
    echo "Updating sistem"
        sudo apt update && sudo apt full-upgrade -s
    echo "20"
        sudo apt install psensor -s
    echo "upgrading sistem"
        sudo apt-get install memtester -s
    echo "50"
        sleep 0.1
    echo "Instaling memteste"
        sudo apt-get install stress-ng -s
    echo "100"
        sleep 0.1
) | zenity --progress --title="RODANDO" \
    --text="Atualizando e instalando programas" \
    --percentage=0 --auto-close
zenity --info --title="Shrek Update" --text="Sistema Atualizado com sucesso"
